# dbt profiles configuration for Punk Brewery project

punk_brewery:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: punk_brewery_dw
      location: US
      threads: 4
      timeout_seconds: 300
      priority: interactive
      retries: 1
      
    prod:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: punk_brewery_dw_prod
      location: US
      threads: 8
      timeout_seconds: 600
      priority: batch
      retries: 2
